{
 "title": "Spanmetrics Demo Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(calls_total[$__range])))"
    }
   },
   {
    "name": "span_name",
    "query": {
     "query": "query_result(sum ({__name__=~\".*calls_total\",service_name=~\"$service\"})  by (span_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate({__name__=~\".*duration_.+seconds_bucket\", service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,service_name)))",
     "legendFormat": "{{le}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (service_name) (rate(calls_total{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean ERROR Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(rate(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "span_names Level - Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 7 span_names and Errors  (APM Table)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(7, sum(rate(calls_total{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name)) "
    },
    {
     "expr": "topk(7, sum(rate(calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name))"
    }
   ]
  },
  {
   "title": "span_name Level - Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 3x3 - span_name Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate({__name__=~\".*duration_.+seconds_bucket\", service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,span_name)))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (span_name,service_name)(increase({__name__=~\".*duration_milliseconds_sum\", service_name=~\"${service}\", span_name=~\"$span_name\"}[5m]) / increase({__name__=~\".*duration_milliseconds_count\", {service_name=~\"${service}\",span_name=~\"$span_name\"}[5m\n])))",
     "legendFormat": "{{span_name}} [{{service_name}}]"
    }
   ]
  },
  {
   "title": "Top 7 Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(7,sum by (span_name,service_name)(increase({__name__=~\".*duration_milliseconds_sum\", service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval]) / increase({__name__=~\".*duration_milliseconds_count\", {service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval])))",
     "legendFormat": "[{{service_name}}]  {{span_name}}"
    }
   ]
  }
 ]
}